name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  otp-version: 23.0.2
  elixir-version: 1.11.3

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}

      - name: Cache mix deps
        uses: actions/cache@v2
        env:
          cache-name: mix-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.otp-version }}-${{ env.elixir-version }}-${{ env.cache-name }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}

      - name: Cache mix deps
        uses: actions/cache@v2
        env:
          cache-name: mix-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.otp-version }}-${{ env.elixir-version }}-${{ env.cache-name }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile --skip-umbrella-children
      - run: MIX_ENV=test mix do compile, test
